---
- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

